version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: innos
    container_name: innos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - innos

  react:
    build:
      context: ./react-news-app # Path to the React frontend app
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Map the React app to port 3000 on the host machine
    volumes:
      - ./react:/app # Mount the React app directory

  db:
    image: mysql:8.0
    container_name: innos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - innos

  nginx:
    image: nginx:alpine
    container_name: innos-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - innos

networks:
  innos:
    driver: bridge